name: Playwright Java Tests

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Playwright Browsers
        run: mvn exec:java -Dexec.mainClass="com.microsoft.playwright.CLI" -Dexec.args="install"

      # Run tests in headless mode
      - name: Run Tests - Headless
        run: mvn clean test -Dheadless=true

      # Run tests in headed mode using xvfb for GUI
      - name: Run Tests - Headed (Non-Headless)
        run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' mvn test -Dheadless=false

      # Show console test report in logs
      - name: Show Test Reports
        run: cat target/surefire-reports/*.txt

      # Upload HTML reports as artifact
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-reports
          path: target/surefire-reports
