name: Playwright Java CI

on:
  schedule:
    - cron: "*/1 * * * *" # Runs every 1 minute
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run Tests
        run: mvn test
