name: Playwright Java Tests with Docker

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t playwright-java-demo .

      - name: Run Playwright Tests in Docker
        run: docker run --rm -v ${{ github.workspace }}/reports:/app/reports -v ${{ github.workspace }}/screenshots:/app/screenshots -v ${{ github.workspace }}/videos:/app/videos playwright-java-demo

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: reports

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: failed-screenshots
          path: screenshots

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        with:
          name: browser-videos
          path: videos
