name: Playwright Java Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run Playwright tests (non-headless)
        run: mvn test -Dheadless=false

      - name: List generated files
        run: ls -R

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            reports/**
            target/surefire-reports/**
            screenshots/**
